# Generated by Django 5.0.6 on 2024-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HisoricalPerformance",
            new_name="HistoricalPerformance",
        ),
    ]
