# Generated by Django 5.0.6 on 2024-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_rename_hisoricalperformance_historicalperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="fullfillment_rate",
            field=models.FloatField(default=0, null=True),
        ),
    ]
