# Generated by Django 5.0.6 on 2024-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0004_alter_historicalperformance_fullfillment_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="fullfillment_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
