# Generated by Django 5.0.6 on 2024-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0005_alter_historicalperformance_fullfillment_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="quality_rating_avg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
