# Generated by Django 5.0.6 on 2024-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0008_alter_historicalperformance_average_response_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="average_resonse_time",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=0, null=True),
        ),
    ]
